### ISSUE TITLE
Issue with arabic language

### ISSUE THREAD

**Issue by monkiki** [bbottema/rtf-to-html#12]
The converted text is unreadable:

![image](https://github.com/bbottema/rtf-to-html/assets/130590/0ffeefde-b295-40ac-aa3b-88484afc251a)

**Comment by bbottema** [comment]
I think the latest version 1.1.0 may have fixed this. If not, please provide a .msg files that contains this issue.

**Comment by bbottema** [comment]
Duplicate of #13 (probably)

**Comment by monkiki** [comment]
> I think the latest version 1.1.0 may have fixed this. If not, please provide a .msg files that contains this issue.

Seems to be solved with latest version. 

Thanks!
