### ISSUE TITLE
RTF2HTMLConverterRFCCompliant doesn't handle mixed charsets

### ISSUE THREAD

**Issue by Yspadadden** [bbottema/rtf-to-html#9]
In cases where a .rtf contains text in different languages that use different charset codepages, only the main codepage is used for decoding of characters. 

This is how it should look:
<img width="425" alt="Screenshot 2021-09-19 at 10 39 00" src="https://user-images.githubusercontent.com/1643274/133921177-a1d8dcf7-7371-4685-9cab-8477575d4c25.png">

This is how it actually looks: 
<img width="441" alt="Screenshot 2021-09-19 at 10 40 52" src="https://user-images.githubusercontent.com/1643274/133921182-3d74d8b4-d608-4398-97f6-38d72a9bec40.png">

In this particular case, we have the following font definition in the fonttable: `{\f6\fswiss\fcharset128 "MS Mincho";}`
Charset 128 in rtf parlance is (according to [wikipedia](https://en.wikipedia.org/wiki/Rich_Text_Format)) `Windows-932`: Japanese. 

The text itself then contains `{\f6\fs24\htmlrtf0 \'8d\'9f\'92\'76\'8c\'68\'97\'e7\htmlrtf\f5}` which references `\f6` in the font table and tells us to interpret the bytes in codepage `Windows-932`. However, the code only uses the main Codepage of the document, which in this case is `\ansicpg1252` or "Latin Alphabet, Western Europe / Americas". 

The solution would be to read the font table definitions and map the definitions to a Charset. Then use this Charset, falling back to the main Charset of the document, if we don't have a specific one for this font. I will attempt to fix this in a pull request.

**Comment by bbottema** [comment]
Great bug report! I see that you're doing excellent work in your branch already.
